### PR TITLE
Adds character skipping functionality

### PR DESCRIPTION
**Pull request by Gudine**
I've developed a way to skip characters, since you asked for it, though you might want to rework the UI elements.

### CODE REVIEW

**Comment by Zanes** [comment]
I didn't expect you to try and make it!
But to be honest it doesn't seem to be working so well, the character I skip really stops showing on the sorting, but in the results what isn't showing is some other character. Apparently if I skip in the first round it's 100% to not work correctly.
Also if the list is too small and so on.
But I'll keep testing and I'll take a closer look.

Suggestion if you'll keep trying: Maybe just skipping both in a round/matchup is easier.

**Comment by Gudine** [comment]
I fixed a bug in the code related to the results screen. That should at least fix the small list issue, if not all of them, but I can't really test with the really big lists since I don't know enough about Saint Seiya. I did test with 20~ characters in the pool though, and it did work.

**Comment by Zanes** [comment]
I think now the results get it wrong whenever I skip more than 1 character. I tried to see if it was only if I skip two in a row but it doesn't matter.

**Comment by Gudine** [comment]
Can you send me the link of one of those sorts, and the characters you actually skipped?

**Comment by Zanes** [comment]
Here's two quick tests:

Series : Only Soul of Gold (9 characters)
saintseiyasorter/index.html?IwdmCYRAOAGbrmgFgD4DYCc7zFcWAwow02c4SvAI1VlWgBp7L7z32D8qqg
Skip Nidhogg Fafner - Battle 2
Skip Eikschnir Surt - Battle 6
Results: Fafner showing up on Rank 7

saintseiyasorter/index.html?IwdmCYRAOcGZgDYwB8TgAx2i4wP6F4H4EkoBGKGKiANBneLvtRux2S3j0A
Skip Loki - Battle 3
Skip Tanngrisnir Heracles - Battle 6
Skip Andreas Rize - Battle 12
Results: Heracles showing up on Rank 6 and Andreas Rize on Rank 5

**Comment by Gudine** [comment]
They seem to work fine for me after the fix... I turned on GitHub Pages for my repo so you can look at them:
https://gudine.github.io/saintseiyasorter/?IwdmCYRAOAGbrmgFgD4DYCc7zFcWAwow02c4SvAI1VlWgBp7L7z32D8qqg
https://gudine.github.io/saintseiyasorter/?IwdmCYRAOcGZgDYwB8TgAx2i4wP6F4H4EkoBGKGKiANBneLvtRux2S3j0A
Maybe the branch you're running the code from wasn't updated

**Comment by Zanes** [comment]
That's weird, I made sure to pull the branch but I guess it really is working now. Gonna merge it since seems to be working fine now. Thank you very much!

**Pull request merged**
